rails/modulo_3/projeto_teste/config/routes.rb
Rails.application.routes.draw do
  resources :type_users
  resources :users
  root to: "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails/modulo_3/projeto_teste/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/modulo_3/projeto_teste/app/models/type_user.rb
class TypeUser < ApplicationRecord
  has_many :users
end

rails/modulo_3/projeto_teste/app/models/user.rb
class User < ApplicationRecord
  belongs_to :type_user
end

rails/modulo_3/projeto_teste/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/modulo_3/projeto_teste/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

rails/modulo_3/projeto_teste/app/controllers/type_users_controller.rb
class TypeUsersController < ApplicationController
  before_action :set_type_user, only: %i[ show edit update destroy ]

  # GET /type_users or /type_users.json
  def index
    @type_users = TypeUser.all
  end

  # GET /type_users/1 or /type_users/1.json
  def show
  end

  # GET /type_users/new
  def new
    @type_user = TypeUser.new
  end

  # GET /type_users/1/edit
  def edit
  end

  # POST /type_users or /type_users.json
  def create
    @type_user = TypeUser.new(type_user_params)

    respond_to do |format|
      if @type_user.save
        format.html { redirect_to type_user_url(@type_user), notice: "Type user was successfully created." }
        format.json { render :show, status: :created, location: @type_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_users/1 or /type_users/1.json
  def update
    respond_to do |format|
      if @type_user.update(type_user_params)
        format.html { redirect_to type_user_url(@type_user), notice: "Type user was successfully updated." }
        format.json { render :show, status: :ok, location: @type_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_users/1 or /type_users/1.json
  def destroy
    @type_user.destroy

    respond_to do |format|
      format.html { redirect_to type_users_url, notice: "Type user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_user
      @type_user = TypeUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_user_params
      params.require(:type_user).permit(:description_name, :criar, :atualizar, :deletar, :visualizar)
    end
end

rails/modulo_3/projeto_teste/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :set_type_user_options, only: [:new, :create, :edit, :update]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :age, :cpf, :telephone, :type_user_id)
    end

    def set_type_user_options
      @type_users_options = TypeUser.all.pluck(:description_name, :id)
    end
end

rails/modulo_3/projeto_teste/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/modulo_3/projeto_teste/app/helpers/home_helper.rb
module HomeHelper
end

rails/modulo_3/projeto_teste/app/helpers/type_users_helper.rb
module TypeUsersHelper
  def get_users(id)
    User.select(:first_name).where(type_user_id: id)
  end
end

rails/modulo_3/projeto_teste/app/helpers/users_helper.rb
module UsersHelper
end

rails/modulo_3/projeto_teste/app/views/home/_menu.html.erb
<nav>
  <ul>
    <li><%=link_to "Adicionar usuário", users_path%></li>
    <li><%=link_to "Adicionar tip de usuário", type_users_path%></li>
  </ul>
</nav>

rails/modulo_3/projeto_teste/app/views/home/index.html.erb
<div>
  <%= link_to "Cadastrar usuário", users_path %>
  <br>
  <%= link_to "Tipos usuário", type_users_path %>
</div>

rails/modulo_3/projeto_teste/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoTeste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/modulo_3/projeto_teste/app/views/type_users/_form.html.erb
<%= form_with(model: type_user) do |form| %>
  <% if type_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_user.errors.count, "error") %> prohibited this type_user from being saved:</h2>

      <ul>
        <% type_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description_name %>
    <%= form.text_field :description_name %>
  </div>

  <div class="field">
    <%= form.label :action %>
    <%= form.text_field :action %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails/modulo_3/projeto_teste/app/views/type_users/edit.html.erb
<h1>Editing Type User</h1>

<%= render 'form', type_user: @type_user %>

<%= link_to 'Show', @type_user %> |
<%= link_to 'Back', type_users_path %>

rails/modulo_3/projeto_teste/app/views/type_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Type Users</h1>

<table>
  <thead>
    <tr>
      <th>Tipo de Usuário</th>
      <th>Criar</th>
      <th>Atualizar</th>
      <th>Deletar</th>
      <th>Vizualizar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_users.each do |type_user| %>
      <tr>
        <td><%= type_user.description_name %></td>
        <td><%= type_user.criar %></td>
        <td><%= type_user.atualizar %></td>
        <td><%= type_user.deletar %></td>
        <td><%= type_user.visualizar %></td>
        <td><%= link_to 'Show', type_user %></td>
        <td><%= link_to 'Edit', edit_type_user_path(type_user) %></td>
        <td><%= link_to 'Destroy', type_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% users = get_users(type_user.id) %>
      <% users.each do |user|%>
        <tr>
          <td><%=  user.first_name %></td>
        </tr> 
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type User', new_type_user_path %>

rails/modulo_3/projeto_teste/app/views/type_users/new.html.erb
<h1>New Type User</h1>

<%= render 'form', type_user: @type_user %>

<%= link_to 'Back', type_users_path %>

rails/modulo_3/projeto_teste/app/views/type_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description name:</strong>
  <%= @type_user.description_name %>
</p>

<p>
  <strong>Action:</strong>
  <%= @type_user.action %>
</p>

<%= link_to 'Edit', edit_type_user_path(@type_user) %> |
<%= link_to 'Back', type_users_path %>

rails/modulo_3/projeto_teste/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nome" %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label "Sobrenome" %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label "Idade" %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label "CPF"%>
    <%= form.number_field :cpf %>
  </div>

  <div class="field">
    <%= form.label "Telefone" %>
    <%= form.number_field :telephone %>
  </div>
  <div class="field">
    <%= form.label "Tipo de usuário" %>
    <%= form.select("type_user_id",  @type_users_options, {include_blank: "Selecione"}, required: true) %>
  </div>
 
  <div class="actions"> 
    <%= form.submit %>
  </div>
<% end %>

rails/modulo_3/projeto_teste/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

rails/modulo_3/projeto_teste/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Idade</th>
      <th><abbr tittle="Certidão de Pessoal Física">CPF</abbr></th>
      <th>Telefone</th>
      <th>Tipo de usuário</th>
      <th>Tipo teste</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.age %></td>
        <td><%= user.cpf %></td>
        <td><%= user.telephone %></td>
        <td><%= user.type_user.description_name %></td>
        <td><%= link_to t('links.show'), user %></td>
        <td><%= link_to t('links.edit'), edit_user_path(user) %></td>
        <td><%= link_to t('links.destroy'), user, method: :delete, data: { confirm: t('confirmacao.deletar') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar usuário', new_user_path %>
<%= link_to 'Voltar', root_path %>

rails/modulo_3/projeto_teste/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

rails/modulo_3/projeto_teste/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @user.cpf %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @user.telephone %>
</p>

<p>
  <strong>Tipo de usuário:</strong>
  <%= @user.type_user.description_name %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>